[WIP] Template editor
PopulateTools/gobierto pull request #1180
Opened 2017-11-24 10:10 UTC by furilo

Starts with #1169 

### What does this PR do?

- [ ] Basic markup in the sandbox for the template editor
- [ ] Integration: for the moment we'll be able to edit gobierto_participation/welcome/index.html.erb, also using #1168 

### How should this be manually tested?

Browse to http://madrid.gobierto.dev/sandbox/admin_sites_site_templates

2017-12-04 11:57 UTC, ferblape requested changes
Also, could you add a data migration that creates the first Template?

2017-12-04 11:57 UTC, ferblape commented on test/fixtures/gobierto_core/site_templates.yml
> +madrid_participation_index:
Could we add a test to check that this template is rendered instead of the regular view?

2017-12-04 11:57 UTC, ferblape commented on lib/liquid/gobierto_common/tags/render_partial.rb
> +    context.registers[:controller].dup.render(partial: @partial_name.strip)
Move the `.strip` to the initialize, so it'll be stripped always.

2017-12-04 11:57 UTC, ferblape commented on lib/liquid/gobierto_common/filters/image_filter.rb
> +# frozen_string_literal: true
Add this new tag to docs/liquid-templates

2017-12-04 11:57 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_core/site_templates_controller.rb
> +      def find_site_template
Filter by current_site

2017-12-04 11:57 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_core/templates_controller.rb
> +      def form
Are you sure this action is necessary? Right now does nothing if I'm not wrong.

2017-12-04 14:32 UTC, apradillap commented
@ferblape, I corrected all your changes requested

2017-12-04 15:09 UTC, ferblape requested changes
Thanks for the changes, but I need to ask you one more thing: I have been able to write ERB tags and do queries to the database:

```
<% current_site = Site.last %>
<%= current_site.domain %>
```

We should strip ERB tags to avoid this security issue.

BTW, in the default template you are using ERB in the styles: `<%= image_url('illustrations/oldlady.svg') %>`

2017-12-05 11:26 UTC, apradillap commented
@ferblape ready!:
- Clean default participation welcome index template without erb tags
- Strip ERB tags in templates. [http://participacion.gobify.net/admin/gobierto_core/templates](http://participacion.gobify.net/admin/gobierto_core/templates). Note: as page level also makes a render_liquid, if you try to put ERB tags, it shows them as text, doesn't execute them.

2017-12-05 12:10 UTC, ferblape approved these changes
👍

2017-12-05 12:11 UTC, merged