Header & CMS site
PopulateTools/gobierto pull request #1181
Opened 2017-11-24 13:56 UTC by Crashillo

### What does this PR do?

1. Includes [Getafe CMS sandbox view](http://madrid.gobierto.dev/sandbox/home_cms.html)
2. Fully redesign gobierto header all around 

### Pending

- Mobile view. For the time being, is just a 1st approach. Lack of some functions (login, account e.g.) 

### Considerations
Sandbox mockups turned to use actual header & footer. Keep that in mind.

2017-11-30 11:08 UTC, furilo requested changes

2017-11-30 11:08 UTC, furilo commented on app/assets/stylesheets/comp-site_header.scss
> +  $cBlue: #0065C8;
we have the colors specified in other place

2017-11-30 11:08 UTC, furilo commented on app/views/layouts/_header.html.erb
> +        <div class="site_header_slogan">
this was not meant to be converted to HTML, it was part of the logo in that specific case

2017-11-30 11:08 UTC, furilo commented on app/assets/stylesheets/comp-site_header.scss
> +  @mixin font($size: $f6, $color: $cBlue, $weight: $fRegular, $style: normal) {
we should not have this kind of things, which are generic (used by many comps), in this specific place

2017-11-30 11:08 UTC, furilo commented on app/assets/stylesheets/comp-cms.scss
> +$black: #000000;
we have colors definitions in another place

2017-11-30 11:08 UTC, furilo commented on app/views/layouts/_header.html.erb
> +          <%# TODO: This links are static %>
please review original templates, we have dynamic code for this

2017-11-30 11:08 UTC, furilo commented on app/views/layouts/_header.html.erb
> +          <%# TODO: This links are static %>
again, there is dynamic code for this already implemented. this: 

https://github.com/PopulateTools/gobierto/pull/1181/files#diff-faf6482c7d306c24c4e64dcdf191f7f4R113

2017-11-30 11:08 UTC, furilo commented on app/assets/stylesheets/comp-site_header.scss
> +  $wSmall: 568px;
this should be generic so don't belong here

2017-11-30 11:08 UTC, furilo commented on app/assets/stylesheets/comp-site_header.scss
> +  $cBlue: #0065C8;
we should be using $color_main, $color_main_soft etc defined in css-conf.scss. those are the colors and we shouldn't create more (unless there is a very good reason). the screen you had as reference was a "custom theme". 

we are defining those overriding some classes to change colors, directly in the admin of each site (I thought you were already familiar with that). take a look at getafe, mataro, sant feliu... in staging/pro, in "personalizar sitio > html de cabecera". 

so: you should be using always the base colors only

2017-12-01 09:54 UTC, ferblape commented
Lo dejo por el momento hasta que ajustéis las cosas que faltan y estas que añado:

### Página de proceso

La navegación de proceso tiene un Breadcrumb de proceso en la `main-nav` y una navegación secundaria en la `sub-nav`. Habría que ajustar ambas:

![screen shot 2017-12-01 at 10 50 02](https://user-images.githubusercontent.com/17616/33477351-ac7fcbae-d685-11e7-8fef-382184a66a69.png)

### Altos Cargos

Dentro de Cargos, Agendas, Declaraciones o Blogs hay muy poco margen:

![screen shot 2017-12-01 at 10 53 19](https://user-images.githubusercontent.com/17616/33477417-eabab60e-d685-11e7-98f7-4427681a102c.png)

Cuando esté esto listo termino de arreglar los tests, porque dependen un poco en el marcado HTML.

2017-12-01 11:51 UTC, furilo commented
Please review @ferblape 

Things that might be improved, although we may leave for another PR: 

- We should show secondary nav not only for processes, but for all participation as we have now (in the future, it may make sense to show this for all Gobierto)
- When in a Process, maybe add the .active to .main-nav-item ?
- I don't like very much the new position of the follow button. Let's leave it there but we should revisit it.
- Mobile nav is not very good. I'll open another issue.

2017-12-01 16:15 UTC, merged