Show polls in partials
PopulateTools/gobierto pull request #1184
Opened 2017-11-27 13:28 UTC by apradillap

Closes #1168 

### What does this PR do?

An admin can add a helper method in a view 

`
<%= show_poll() %>
<%= show_poll(poll_id) %>
`
show_poll has these characteristics:
- If the admin provides an ID, we select that specific poll
- **If the admin provides an ID and it's answered, we select between all the open, public and not answered polls by the user (extra)**
- If no ID is provided, we select between all the open and public polls
- If no ID is provided and the user is logged in, we select between all the open, public and not answered polls by the user
- The method would use the partial we currently have in the home page.

### How should this be manually tested?

From /participation

### Styles

The participate button when we hover the mouse over it, you don't see correctly. It's broken since we modified the follow_button in the header.

2017-11-29 07:12 UTC, ferblape requested changes

2017-11-29 07:12 UTC, ferblape commented on app/helpers/application_helper.rb
> +    poll = GobiertoParticipation::Poll.find(poll_id) if poll_id
Filter by current_site

2017-11-29 07:12 UTC, ferblape commented on app/helpers/application_helper.rb
> +    render partial: "shared/polls", locals: { poll_id: poll_id }
I'd check here here also that the poll is from the current site.

If the poll id is wrong I would return `render nothing: true`

2017-11-29 07:12 UTC, ferblape commented on app/helpers/application_helper.rb
> +        else
Use `elsif` to save a couple of lines.

2017-11-29 07:12 UTC, ferblape commented on app/helpers/application_helper.rb
> +      else
Use `elsif`

2017-11-29 07:12 UTC, ferblape commented on app/helpers/application_helper.rb
> +    answerable_polls_by_user = answerable_polls.select { |p| p.answerable_by?(current_user) } if current_user
Use `.detect` to avoid doing `.first` later.

2017-11-29 07:12 UTC, ferblape commented on app/views/shared/_polls.html.erb
> +  <% if next_poll.is_a?(::GobiertoParticipation::Poll) %>
`next_poll(poll_id)`, right?

2017-11-29 07:12 UTC, ferblape commented on app/views/shared/_polls.html.erb
> +  <% if next_poll.is_a?(::GobiertoParticipation::Poll) %>
In that case to avoid calling next_poll two times assign it to a variable `poll = next_poll(poll_id)` and check if poll is present.

2017-11-29 08:03 UTC, furilo commented
- [ ] You are showing the title of the poll, the idea was to show the title of the question +  the options (as per the sandbox). Although maybe it makes sense to show both... Although we may quickly ran out of space. Lets for the moment include poll title, first question + options. 
- [ ] If I'm logged out, click on participate, the modal appears, I do login, you take me to the home again, forcing me to repeat the action I just did.

2017-12-13 09:44 UTC, furilo commented
- [ ] If you don't specify an id, you get Liquid error: internal - We should be able to just call show_poll() and it should show randomly any of the available polls

2017-12-13 09:50 UTC, apradillap commented
Ok, I'Il add that option

2017-12-13 09:51 UTC, furilo commented
Well, it was something that was working before, right?

2017-12-13 09:57 UTC, apradillap commented
Before the migration to Liquid it worked, I fix it

2017-12-14 11:09 UTC, apradillap commented
@furilo I've added the possibility that show_poll is called without parameters. Deployed in staging

2017-12-20 16:06 UTC, ferblape requested changes
LGTM! Just remove the hardcoded ID and feel free to merge and release.

2017-12-20 16:06 UTC, ferblape commented on app/views/gobierto_participation/welcome/index.liquid
> +        {% show_poll(poll_id: 353021530) %}
Could you remove the hardcoded id?

2017-12-20 20:33 UTC, merged