155 - Person-specific calendar integrations
PopulateTools/gobierto pull request #1186
Opened 2017-11-27 19:37 UTC by amiedes

Closes [#155](https://github.com/PopulateTools/issues/issues/155)

### What does this PR do?

* Deattaches calendar integration configurations from sites so users can chose their own calendar service.
* Makes some work to prepare for when we permit syncing processes events from calendars in a similar way.

![pr-calendar](https://user-images.githubusercontent.com/9287468/33284970-22379a48-d3b1-11e7-9504-bd8fa007aefa.gif)

### How should this be manually tested?

Go to a staging site, configure different calendar integrations for two people in that site, and manually run agendas synchronization.

### Does this PR changes any configuration file?

No

### Future work

* I renamed most of the relevant models, methods, variables etc. A few well-isolated components (`lib/services/gobierto_people/*`) still use names which suggest calendar integrations are only related to people.

2017-11-28 08:39 UTC, amiedes commented
I just realised I need to apply the permissions logic. I'll do this  now.

2017-11-30 15:52 UTC, ferblape requested changes
Great work! There are a few minor detals and the Rollbar I have mentioned. To reproduce it follow these steps:

1. Configure an IBM integration
2. Import events
3. Remove configuration
4. Configure a Google Calendar integration
5. 💥

2017-11-30 15:52 UTC, ferblape commented on app/controllers/gobierto_people/people/google_calendar/authorization_controller.rb
> +          @configuration = ::GobiertoCalendars::GoogleCalendarConfiguration.find_by(collection_id: @person.calendar.id)
This configuration might not exist. See this Rollbar: https://rollbar.com/Populate/gobierto/items/646/

2017-11-30 15:52 UTC, ferblape commented on config/locales/gobierto_admin/gobierto_calendars/models/ca.yml
> +        ibm_notes_usr: La compte
El nom d'usuari

2017-11-30 15:52 UTC, ferblape commented on config/locales/gobierto_admin/gobierto_calendars/models/ca.yml
> +        microsoft_exchange_usr: La compte
El nom d'usuari

2017-11-30 15:52 UTC, ferblape commented on db/data/20171016104939_encrypt_calendar_configuration_credentials.rb
> +    #   next if gp_module_settings.calendar_integration != 'ibm_notes'
Let's remove these comments

2017-11-30 15:52 UTC, ferblape commented on app/forms/gobierto_admin/gobierto_calendars/calendar_configuration_form.rb
> +        @collection ||= ::GobiertoCommon::Collection.find_by(id: collection_id)
Filter by site

2017-11-30 15:52 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_calendars/calendar_configuration_controller.rb
> +        @collection = ::GobiertoCommon::Collection.find(params[:id])
Filter by site

2017-12-01 16:51 UTC, amiedes commented
Fixed 👷

2017-12-04 13:15 UTC, merged