1135 calendar updates button
PopulateTools/gobierto pull request #1246
Opened 2017-12-12 08:13 UTC by entantoencuanto

Related with #1135

### What does this PR do?
Adds a link on admin edition view of calendar configurations to sync the calendar if some integration is defined. Also a new activity is created when a calendar is synchronized. If there are previous calendar update activities the date of last sync is shown next to the link.

### How should this be manually tested?

Visit http://madrid.gobify.net/admin/gobierto_calendars/configurations/29/edit

### Does this PR changes any configuration file?

- Only `config/initializers/subscribers.rb` to include activities related with calendars

2017-12-12 09:27 UTC, ferblape requested changes
Thanks @entantoencuanto, it works great. I have added a couple of small issues in the code review, but I'd like you to add also an integration test. Ping me if you need help mocking the calendar synchronization.

2017-12-12 09:27 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_calendars/calendar_configuration_controller.rb
> +                     else
The `else` is not necessary, isn't it?

2017-12-12 09:27 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_calendars/calendar_configuration_controller.rb
> +        redirect_to edit_admin_calendars_configuration_path(@collection)
Could you add a flash message after the sync? Right now it works but there's no clear feedback for the user that it worked

2017-12-12 09:27 UTC, ferblape commented on app/views/gobierto_admin/gobierto_calendars/calendar_configuration/edit.html.erb
> +    <%= link_to sync_calendars_admin_calendars_configuration_path(@calendar_configuration_form.collection_id), method: :put, data: { confirm: "Are you sure?" } do %>
Missing translation

2017-12-21 07:03 UTC, ferblape commented
Hey @entantoencuanto can this be accepted again?

2017-12-21 08:40 UTC, entantoencuanto commented
Yes, I think so

2017-12-22 09:54 UTC, merged