Markup for phase editing in groups
PopulateTools/gobierto pull request #1248
Opened 2017-12-12 09:05 UTC by furilo

Closes #1234 

### What does this PR do?

- [x] Markup for phase editing
- [ ] Implementation

### How should this be manually tested?

- Markup: Browse to http://madrid.gobierto.dev/sandbox/admin_part_group

### Does this PR changes any configuration file?

- [ ] new environment variable in `.env.example`?
- [ ] new entry in `config/application.yml`?
- [ ] new entry in `config/secrets.yml`?

(Changes in these files might need to update the role in Ansible)

2017-12-28 08:20 UTC, ferblape requested changes
Good job! 

Just review my comments. Most of them are scopes in the queries (we should avoid this error from now on ;)

And a couple of things:

- When editing the phases of the process, in the breadcrumb the title of the process is not visible

- When editing a stage in the breadcrumb says CMS

- In `Process` model:
  - `next_stage` should use the new ordering, not the date
  - same with `showcase_stage`
  - in `current_stage`: remove the comment
  - `self.open` gets all the processes of all the sites. That method is quite dangerous. Is it used somewhere?

- The URL of the Information and Results page should keep the user in the process. Now, it takes the user to the CMS section, and it should be the show action inside the process.

2017-12-28 08:20 UTC, ferblape commented on app/assets/stylesheets/admin/application.scss
> +// @import "codemirror";
Is this correct?

2017-12-28 08:20 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_participation/processes/process_stage_pages_controller.rb
> +          ::GobiertoParticipation::ProcessStage.find(params[:process_stage_id])
Scope: `current_process.stages.find...`

2017-12-28 08:20 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_participation/processes/process_stage_pages_controller.rb
> +          ::GobiertoParticipation::ProcessStagePage.find(params[:id])
Scope: `@process_stage.process_stage_page...`

2017-12-28 08:20 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_participation/processes/process_stages_controller.rb
> +          ::GobiertoParticipation::ProcessStage.find(params[:id])
Scopes...

2017-12-28 08:20 UTC, ferblape commented on app/forms/gobierto_admin/gobierto_participation/process_form.rb
> +          title_translations: { 'en' => 'Information', 'es' => 'Información' },
Could we add Catalan?

2017-12-28 08:20 UTC, ferblape commented on app/forms/gobierto_admin/gobierto_participation/process_stage_form.rb
> +        @process ||= GobiertoParticipation::Process.find_by(id: process_id)
`current_site.processes`

2017-12-28 08:20 UTC, ferblape commented on app/helpers/gobierto_admin/gobierto_participation/process_stages_helper.rb
> +      def admin_stage_url(stage)
The method returns paths, it should be named `admin_stage_path`?

2017-12-28 08:42 UTC, apradillap commented on app/assets/stylesheets/admin/application.scss
> +// @import "codemirror";
Alvaro, estuvo probando "Remove the Codemirror CSS temporarily to see how it feels"
https://github.com/PopulateTools/gobierto/pull/1248/commits/7ae4ea97c093b7572884a79d4422a4c03f09168d @furilo, what do we do?

2017-12-28 08:46 UTC, furilo commented
>
> Alvaro, estuvo probando "Remove the Codemirror CSS temporarily to see how
> it feels"
> 7ae4ea9
> <https://github.com/PopulateTools/gobierto/commit/7ae4ea97c093b7572884a79d4422a4c03f09168d>
> @furilo <https://github.com/furilo>, what do we do?
>

Don’t use it, we can remove the commented reference


-- 
http://twitter.com/furilo
http://www.furilo.com

2017-12-28 13:24 UTC, apradillap commented
@ferblape I've corrected all the "requested changes" except `next_stage` and `showcase_stage` in `Process` model that are returning stages 😄 
Highlights: I deleted `self.open` dangerous method, I'll check the scopes in future PRs, thanks!!

2017-12-29 06:24 UTC, ferblape commented
Thanks @apradillap just two more details I have just noticed:

![screen shot 2017-12-29 at 07 20 27](https://user-images.githubusercontent.com/17616/34430775-e61ccbe8-ec68-11e7-9ef5-5f2f87e2c20f.png)

1. "More information" button should only be visible if there's a phase with the Information tool published. Otherwise, the link is broken and raises this error: https://rollbar.com/Populate/gobierto/items/692/

2. The markup in the stages navigator for the first stage is wrong. In the example above the active stage is the second one, but the first stage is bold too, and the user can't distinguish which is the active stage.

Feel free to release after fixing these two issues 🚀

2017-12-29 06:27 UTC, ferblape commented
Also @apradillap could you reference in the PR all the issues it closes? 1238, 1235....

2017-12-29 11:34 UTC, merged