Participation local menu
PopulateTools/gobierto pull request #1330
Opened 2018-01-12 15:51 UTC by apradillap

Closes https://github.com/PopulateTools/issues/issues/207

### What does this PR do?

Add a new template navigation_process

### How should this be manually tested?

You can personalize the template from /admin/gobierto_core/templates

and you'll see in

<img width="1317" alt="captura de pantalla 2018-01-12 a las 16 50 17" src="https://user-images.githubusercontent.com/69764/34883071-c6a8bb0e-f7b8-11e7-9c37-57bb58543128.png">

2018-01-15 13:26 UTC, ferblape requested changes
Looks good but it could be refactored a bit to simplify it.

2018-01-15 13:26 UTC, ferblape commented on app/models/gobierto_core/site_template.rb
> +      GobiertoCore::SiteTemplate.joins(:template).where("gcore_site_templates.site_id = ? AND gcore_templates.template_path = ?",
Could we use `self.class.table_name`?

2018-01-15 13:26 UTC, ferblape commented on app/views/gobierto_participation/layouts/_navigation.sub.html.erb
> +  <%= raw render_liquid(liquid_str) %>
I'd refactor it a bit, too many things to remember when trying to render a template.

I'd like the syntax to be something like: `<%= raw render_liquid("gobierto_participation/layouts/navigation_process") %>

- remove the calls to liquid_str from the view, and move them to the helper
- remove the extension `.liquid` of the template

2018-01-15 13:26 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_core/templates_controller.rb
> +        if ::GobiertoCore::SiteTemplate.current_site_has_custom_template?(current_site, template.template_path)
This is duplicated in `index` and `edit` actions. Could we extract it to a method or filter and remove the duplication?

2018-01-15 17:24 UTC, furilo approved these changes

2018-01-16 07:32 UTC, ferblape approved these changes
👍

2018-01-16 07:32 UTC, merged