Fix subscriptions when referer is not available
PopulateTools/gobierto pull request #1854
Opened 2018-08-13 09:26 UTC by amiedes

Fixes rollbar [#1202](https://rollbar.com/Populate/gobierto/items/1202/occurrences/49905012625/)

## What does this PR do

When creating a new subscription, if the referer is not available it redirects to the home page.

2018-08-23 07:53 UTC, ferblape requested changes

2018-08-23 07:53 UTC, ferblape commented on app/controllers/user/subscriptions_controller.rb
> +        redirect_to(request.referrer || root_path)
There's a new way to do this!

https://blog.bigbinary.com/2016/02/29/rails-5-improves-redirect_to_back-with-redirect-back.html

2018-08-23 07:53 UTC, ferblape commented on app/controllers/meta_welcome_controller.rb
> +      redirect_to(current_site.root_path)
👍

2018-09-03 11:04 UTC, amiedes commented
Done 💅

2018-09-03 11:16 UTC, merged