934 query browser should 939
PopulateTools/gobierto pull request #2827
Opened 2020-01-30 09:18 UTC by jorgeatgu

Closes #N
https://github.com/PopulateTools/issues/issues/939
https://github.com/PopulateTools/issues/issues/934
## :v: What does this PR do?
Don't reload tabs when we switch between them
Run queries from summary and queries(change tab and run selected query)

## :mag: How should this be manually tested?

## :eyes: Screenshots

### After this PR

![switch-tabs 2020-01-30 10_16_51](https://user-images.githubusercontent.com/2649175/73435890-cbdaa900-4349-11ea-8f27-44d55869405e.gif)

2020-01-30 13:42 UTC, Crashillo requested changes

2020-01-30 13:42 UTC, Crashillo commented on app/assets/stylesheets/module-data.scss
> +  .fa-caret-down {
Avoid styling FontAwesome

2020-01-30 13:42 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Queries.vue
> +              @click="runYourQuery(arrayQueries[index].attributes.sql);sendQuery(item); closeModal(); changeTab()"
Too many actions in the DOM. May you call all of them in a method?

2020-01-30 13:42 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Queries.vue
> +              <!-- <i
Remove old code. Let it go, if you come back to this

2020-01-30 13:42 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Queries.vue
> +      numberQueries: Number,
Initialize values, no types. Set `0` instead of `Number`

2020-01-30 13:42 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Queries.vue
> +      totalQueries: Number,
Initialize values, no types. Set `0` instead of `Number`

2020-01-30 13:42 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Queries.vue
> +      this.endPoint = '/api/v1/data/queries?filter[dataset_id]='
Get use to parametize the baseUrl from a different file (or at least outside of the Vue scope)

2020-01-30 13:42 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Queries.vue
> +      this.endPoint = '/api/v1/data/data';
Extract endpoints

2020-01-30 13:42 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/sets/SQLEditorHeader.vue
> +    closable : {
What about to movethis to any common vue function file?

2020-01-30 16:17 UTC, jorgeatgu commented
Ready for test in staging

2020-01-31 14:43 UTC, ferblape commented on app/javascript/gobierto_data/webapp/components/commons/Queries.vue
> +    deleteQuery(index) {
I'd use `id` instead of `index`

2020-02-04 13:49 UTC, Crashillo approved these changes

2020-02-04 14:02 UTC, entantoencuanto approved these changes

2020-02-04 14:02 UTC, merged