940 show users they are using a saved query
PopulateTools/gobierto pull request #2828
Opened 2020-01-30 10:28 UTC by jorgeatgu

Closes #N
https://github.com/PopulateTools/issues/issues/940

## :v: What does this PR do?
When user load query, we show name query, privacy status and edit button

## :eyes: Screenshots

### Before this PR
![before-load-query 2020-01-30 11_26_45](https://user-images.githubusercontent.com/2649175/73441532-6f7c8700-4353-11ea-86e3-dbf80915384e.gif)
### After this PR
![saved-query 2020-01-30 11_25_08](https://user-images.githubusercontent.com/2649175/73441382-35ab8080-4353-11ea-90b0-91d803dab0b1.gif)

2020-01-30 13:47 UTC, Crashillo requested changes

2020-01-30 13:47 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/sets/SQLEditorHeader.vue
> +          @keyup="labelQueryName = $event.target.value; onSave()"
Multiple actions on DOM = method

2020-02-04 10:02 UTC, ferblape commented
Save a query doesn't work, the API returns 422

![Screen Shot 2020-02-04 at 11 01 16](https://user-images.githubusercontent.com/17616/73734304-b694be80-473d-11ea-8fa9-296934c892b4.png)

And the error is that the dataset is blank:

```json
{"errors":[{"source":{"pointer":"/data/attributes/dataset"},"detail":"no pot estar en blanc"}]}
```

2020-02-04 13:45 UTC, jorgeatgu commented
> Save a query doesn't work, the API returns 422
> 
> ![Screen Shot 2020-02-04 at 11 01 16](https://user-images.githubusercontent.com/17616/73734304-b694be80-473d-11ea-8fa9-296934c892b4.png)
> 
> And the error is that the dataset is blank:
> 
> ```json
> {"errors":[{"source":{"pointer":"/data/attributes/dataset"},"detail":"no pot estar en blanc"}]}
> ```

Fixed in staging 
![post-query 2020-02-04 14_43_34](https://user-images.githubusercontent.com/2649175/73750101-e69f8a00-475c-11ea-945a-4fae969379be.gif)

2020-02-04 14:13 UTC, entantoencuanto approved these changes

2020-02-04 16:13 UTC, merged