925 permalinks
PopulateTools/gobierto pull request #2834
Opened 2020-01-31 15:42 UTC by jorgeatgu

Closes #925

## :v: What does this PR do?
Now when we reload the datasets URL's we don't lose the data.

## :mag: How should this be manually tested?
Go to any dataset and reload the browser, check that it has the title, your queries, recent queries, and you can see the table with the data.

2020-01-31 16:06 UTC, Crashillo requested changes

2020-01-31 16:06 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/sets/SQLEditor.vue
> +      this.endPointSlug = `/api/v1/data/datasets/${this.$route.params.id}/meta`
baseUrls out

2020-01-31 16:06 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/pages/DataSets.vue
>        this.endPoint = '/api/v1/data/queries?filter[dataset_id]='
baseUrls out

2020-01-31 16:06 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/pages/DataSets.vue
> +      this.endPoint = `/api/v1/data/datasets/${this.$route.params.id}/meta`
baseUrls out

2020-02-04 17:30 UTC, ferblape commented on app/javascript/gobierto_data/webapp/pages/DataSets.vue
> +          this.idDataset = this.rawData.data.id
two attributes for the same thing? `idDataset` and `datasetId`

2020-02-04 17:30 UTC, ferblape commented on app/javascript/gobierto_data/webapp/pages/DataSets.vue
> +          this.titleDataset = this.rawData.data.attributes.name
duplicated

2020-02-05 15:10 UTC, entantoencuanto approved these changes

2020-02-05 15:24 UTC, merged