2823 permalink for saved queries
PopulateTools/gobierto pull request #2858
Opened 2020-02-11 13:37 UTC by jorgeatgu

Closes #2823 

Created permalinks only for **saved queries**, also for any tab of dataset(summary, queries, editor, visualizations and downloads).

## :v: What does this PR do?

## :mag: How should this be manually tested?

## :eyes: Screenshots

### After this PR

![permalinks 2020-02-11 14_35_45](https://user-images.githubusercontent.com/2649175/74241207-d434cb80-4cdb-11ea-9c9c-d10025632bb3.gif)

2020-03-18 12:32 UTC, Crashillo requested changes

2020-03-18 12:32 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Queries.vue
> +        this.nav(index)
```suggestion
      const { privacy_status = '' } = item.attributes
      if (privacy_status === 'open') {
        this.nav(index)
```

2020-03-18 12:32 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Queries.vue
> +              :href="'/datos/' + pathQueries + '/q/' + index"
```suggestion
              :href="'`/datos/${pathQueries}/q/${index}`"
```

2020-03-18 12:32 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Queries.vue
> +        }, 300)
Why is the reason to show an spinner 300ms? Why don't you move `this.showSpinner = false` to the `then` callback? When you wanna hide the spinner actually.

2020-03-18 12:32 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Queries.vue
> +    }, () => {})
Align this

2020-03-18 12:32 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/sets/Nav.vue
> +import Button from './../commons/Button.vue';
Keep consistency between single/double quotes

2020-03-18 12:32 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/sets/Nav.vue
> +    }, () => {})
Align this

2020-03-18 12:32 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/sets/Nav.vue
> +          title: label
`label` comes from, i.e.`activateTab(0, 'resumen')`. Is this text going to be displayed anywhere? If so, it must be translated. Never use string literals if they're gonna be displayed.

2020-03-18 12:32 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/sets/SQLEditor.vue
> +        v-if="publicQueries"
could `publicQueries` come as `undefined` or `null`? Because if it's an array, you should check `v-if="publicQueries.instead"`

2020-03-18 12:32 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/sets/SQLEditorCode.vue
> +      code: `SELECT * FROM ${this.tableName}`,
Move this to the `created`

2020-03-18 12:32 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/sets/SQLEditorHeader.vue
> +        this.codeQuery = this.publicQueries[codeQueryFromRoute].attributes.sql
(deep cough) 🤧 🤧 ...destructuring... cough, cough!

2020-04-13 09:09 UTC, entantoencuanto approved these changes

2020-04-13 09:09 UTC, merged