Dont list items without content
PopulateTools/gobierto pull request #3010
Opened 2020-04-24 16:23 UTC by jorgeatgu

Closes #2914

## :v: What does this PR do?

In the Categories don't show items without content.

## :mag: How should this be manually tested?

Staging

Before
![before_categories](https://user-images.githubusercontent.com/2649175/80234559-a7e0e800-8658-11ea-82cd-f1dc75446ea9.png)

After
![after_categories](https://user-images.githubusercontent.com/2649175/80234564-aadbd880-8658-11ea-975e-430b85b71864.png)

2020-04-24 16:48 UTC, furilo commented
If you select a category the frecuency gets filtered; but if you deselect the category, the frecuencies don't revert to the initial state.

2020-04-27 09:30 UTC, Crashillo requested changes

2020-04-27 09:30 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/sidebar/SidebarCategories.vue
> +              v-for="option in filteredOptions(filter)"
Desestructure `option`

2020-04-27 09:30 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/sidebar/SidebarCategories.vue
> +      return filter.options.filter(element => element.counter > 0);
Desestructure `element`. `counter` may be missing

2020-04-28 05:52 UTC, ferblape approved these changes
Nothing to add

2020-04-30 08:31 UTC, Crashillo approved these changes

2020-04-30 09:27 UTC, merged