Includes some improvements when working with queries and visualizations
PopulateTools/gobierto pull request #3029
Opened 2020-05-06 08:19 UTC by jorgeatgu

Closes #2973 

[ WIP ]

## :v: What does this PR do?

Includes a fork button when we loaded a query that is not ours.
Increases the width of the input if the name of the query is too large.
Showed string "consulta modificada" when modified the query on editor.

## :mag: How should this be manually tested?

Staging

## :eyes: Screenshots

### Before this PR

### After this PR

2020-05-18 07:48 UTC, Crashillo commented
Solve the conflicts first. Are you currently working on this? If so, set it as draft in the meantime, it's faster to detect it.

2020-05-18 08:11 UTC, jorgeatgu commented
> Solve the conflicts first. Are you currently working on this? If so, set it as draft in the meantime, it's faster to detect it.

Conflicts resolved. You can review

2020-05-18 09:03 UTC, Crashillo requested changes

2020-05-18 09:03 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/Dataset.vue
> +    QueryIsNotMine() {
camelCase 🐫

2020-05-18 09:03 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/SavingDialog.vue
> +      }
Back to the old times. Why is this here? In the saving dialog? Didn't we move it to the Dataset (the parent) component?

2020-05-18 09:03 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/SavingDialog.vue
> +      }
Whaaaaaaaaaat?

2020-05-18 12:50 UTC, jorgeatgu commented on app/javascript/gobierto_data/webapp/components/commons/SavingDialog.vue
> +      }
I have an explanation for this, check if the user is logged in or not should be the first thing when the user click the button. If we move this to the dataset, we're emitting an event and doing checks to finally send the user to the login, better to send it first, right? And we need this to check if the user is logged in when trying to save a visualization.

2020-05-18 12:51 UTC, jorgeatgu commented on app/javascript/gobierto_data/webapp/components/commons/SavingDialog.vue
> +      }
haaaaaappeeens?

2020-05-19 08:31 UTC, Crashillo approved these changes

2020-05-19 08:31 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/SavingDialog.vue
> +      }
The absolute numbers there, in the style width. They're yelling: why!?

2020-05-19 09:51 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/SavingDialog.vue
> +      }
My idea is about sending a prop (I don't know if it already exists), something like `isUserLogged`, a boolean, so when this component is rendered, already it knows the status, and display/hide stuff consequently. No querying at all, just a flag

2020-05-20 05:04 UTC, merged