Dashboards: Costs Table
PopulateTools/gobierto pull request #3129
Opened 2020-06-03 11:31 UTC by jorgeatgu

Closes https://github.com/PopulateTools/issues/issues/1049

## :v: What does this PR do?

Create a new section for the dashboard with the cost table. This table contains two sublevels and the item of each of the costs.

## :mag: How should this be manually tested?

## :eyes: Screenshots

### After this PR

![dashboard_costes 2020-06-03 13_21_57](https://user-images.githubusercontent.com/2649175/83631101-45570200-a59d-11ea-9565-1377721369ab.gif)

2020-06-03 14:08 UTC, ferblape commented on app/views/gobierto_dashboards/dashboards/costs.html.erb
> +       data-home-url="<%= gobierto_dashboards_contracts_summary_url %>"
This URL should be gobierto_dashboards_costs_summary_url

2020-06-03 14:08 UTC, ferblape commented on config/locales/gobierto_dashboards/views/ca.yml
> +        total: Coste total
Cost total

2020-06-03 14:09 UTC, ferblape commented on config/locales/gobierto_dashboards/views/ca.yml
> +          costs: Costes
Costos

2020-06-03 14:11 UTC, ferblape reviewed
This looks great ;)

2020-06-03 16:19 UTC, Crashillo requested changes

2020-06-03 16:19 UTC, Crashillo commented on app/assets/stylesheets/module-dashboards.scss
> +    color: #666;
Static colors?

2020-06-03 16:19 UTC, Crashillo commented on app/assets/stylesheets/module-dashboards.scss
> +        border-color: rgba(33, 150, 83, .2);
Static colors?

2020-06-03 16:19 UTC, Crashillo commented on app/assets/stylesheets/module-dashboards.scss
> +    color: rgba(102, 102, 102, .5);
Static colors?

2020-06-03 16:19 UTC, Crashillo commented on app/assets/stylesheets/module-dashboards.scss
> +    border-left: 7px solid rgba(1, 120, 168, .2);
Static colors?

2020-06-03 16:19 UTC, Crashillo commented on app/assets/stylesheets/module-dashboards.scss
> +    color: #666;
Static colors?

2020-06-03 16:19 UTC, Crashillo commented on app/javascript/gobierto_dashboards/index.js
> +  //FIX-ME
FIXME still on? If so, provide explanation

2020-06-03 16:19 UTC, Crashillo commented on app/javascript/gobierto_dashboards/modules/costs_controller.js
> +      Promise.all([getRemoteData(options.costsEndpoint)]).then((rawData) => {
Perhaps you don't need to do a Promise.all if you have just one promise

2020-06-03 16:19 UTC, Crashillo commented on app/javascript/gobierto_dashboards/modules/costs_controller.js
> +    const amountStrings = [ 'cd_bens_i_serveis', 'cd_cost_personal', 'cost_directe_2018' , 'cost_indirecte_2018', 'cost_total_2018', 'costpers2018', 'costrestadir2018', 'cost_per_habitant', 'ingresso
Hmmmm, static texts? why so?

2020-06-03 16:19 UTC, Crashillo commented on app/javascript/gobierto_dashboards/modules/costs_controller.js
> +        if (d.cost_directe_2018) {
This function (setGlobalVariables) are very very very specific to a site. Perhaps we should think in configuration file? cc/ @ferblape

2020-06-03 16:19 UTC, Crashillo commented on app/javascript/gobierto_dashboards/webapp/containers/costs/Detail.vue
> +    <Table
If you move the classes to the Table componet, does the markup break? If don't, you may remove the outer `div`

2020-06-03 16:19 UTC, Crashillo commented on app/javascript/gobierto_dashboards/webapp/containers/costs/Distribution.vue
> +
It's really difficult, I'd say almost impossible, to figure out what this function does 😸

2020-06-03 16:19 UTC, Crashillo commented on app/javascript/gobierto_dashboards/webapp/containers/costs/TableFirstLevel.vue
> +        v-for="{ agrupacio, cost_directe_2018, cost_indirecte_2018, cost_total_2018, cost_per_habitant, ingressos, respecte_ambit, ordre_agrupacio } in groupData"
The bad point of this is about we are strongly linking the Costs component, to the results of an specific API (from a Catalonia place). That implies, these components aren't gonna work with any different endpoints. Is this OK? cc/ @ferblape

2020-06-03 16:19 UTC, Crashillo commented on app/javascript/gobierto_dashboards/webapp/containers/costs/TableFirstLevel.vue
> +      let dataGroup = []
What if you preprocess all this data calculations before the vue-app starts? In this way you won't require to spend processing time when the component is mounted/unmounted...

2020-06-03 16:19 UTC, Crashillo commented on app/javascript/gobierto_dashboards/webapp/containers/costs/TableItem.vue
> +          v-for="{ agrupacio, nomact, cost_directe_2018, cost_indirecte_2018, cost_total_2018, cost_per_habitant, ingressos, respecte_ambit } in dataGroup"
Similar as I asked before

2020-06-03 16:19 UTC, Crashillo commented on app/javascript/gobierto_dashboards/webapp/containers/costs/TableItem.vue
> +    totalIncomes() {
Good use of the computed props, young Padawan

2020-06-03 16:19 UTC, Crashillo commented on app/javascript/gobierto_dashboards/webapp/containers/costs/TableSubHeader.vue
> +    agrupacioData(id) {
This is quite similar to the other calculation I suggested to move outside, isn't?

2020-06-08 07:14 UTC, jorgeatgu commented on app/javascript/gobierto_dashboards/webapp/containers/costs/Distribution.vue
> +
so sorry, bubbles chart are for the next PR

2020-06-08 08:53 UTC, jorgeatgu commented on app/javascript/gobierto_dashboards/modules/costs_controller.js
> +    const amountStrings = [ 'cd_bens_i_serveis', 'cd_cost_personal', 'cost_directe_2018' , 'cost_indirecte_2018', 'cost_total_2018', 'costpers2018', 'costrestadir2018', 'cost_per_habitant', 'ingresso
I need to convert to `Numbers` the values that come as formatted strings as "1,134,345.45". So, i've created an array with those values

2020-06-09 10:23 UTC, Crashillo approved these changes
The comments I made are about functional logic. If you all are OK having such strong link between the application and one particular client, go ahead.

2020-06-09 10:23 UTC, Crashillo commented on app/javascript/gobierto_dashboards/modules/costs_controller.js
> +    const amountStrings = [ 'cd_bens_i_serveis', 'cd_cost_personal', 'cost_directe_2018' , 'cost_indirecte_2018', 'cost_total_2018', 'costpers2018', 'costrestadir2018', 'cost_per_habitant', 'ingresso
My point of this was that you're binding these column names to the application. As you can see, the names comes from Mataró, so you're setting this code to be full-dependant of Mataró fields. Barcelona costs? doesn't work. Zaragoza costs? doesn't work. Marbella costs? doesn't work.

2020-06-09 10:23 UTC, Crashillo commented on app/javascript/gobierto_dashboards/modules/costs_controller.js
> +      if (d.cost_directe_2018) {
Same as I mentioned previously

2020-06-09 10:23 UTC, Crashillo commented on app/javascript/gobierto_dashboards/webapp/containers/costs/TableFirstLevel.vue
> +        v-for="{ agrupacio, cost_directe_2018, cost_indirecte_2018, cost_total_2018, cost_per_habitant, ingressos, respecte_ambit, ordre_agrupacio } in groupData"
Same as I mentioned previously

2020-06-09 10:23 UTC, Crashillo commented on app/javascript/gobierto_dashboards/webapp/containers/costs/TableSubHeader.vue
> +        v-for="{ agrupacio, cost_directe_2018, cost_indirecte_2018, cost_total_2018, cost_per_habitant, ingressos, respecte_ambit } in dataGroup"
Same

2020-06-09 13:21 UTC, ferblape commented on app/javascript/gobierto_dashboards/webapp/containers/costs/TableFirstLevel.vue
> +        v-for="{ agrupacio, cost_directe_2018, cost_indirecte_2018, cost_total_2018, cost_per_habitant, ingressos, respecte_ambit, ordre_agrupacio } in groupData"
Yes, this is fine for the time being. For the moment this is a customized dashboard for this client. It should be moved to an engine at some point but for the moment we'll keep it in Gobierto core.

2020-06-09 14:07 UTC, ferblape commented
Closed in favor of #3145

2020-06-09 14:07 UTC, closed without merging