Gobierto Data: check if the user loads an invented dataset
PopulateTools/gobierto pull request #3179
Opened 2020-06-23 16:17 UTC by jorgeatgu

Closes #3154 

## :v: What does this PR do?

Check if the user loads an invented dataset, in this case, redirect the user to dataset list

## :mag: How should this be manually tested?

Staging

## :eyes: Screenshots

### After this PR
![after](https://user-images.githubusercontent.com/2649175/85428309-44eacf00-b57d-11ea-9081-37da2d64641b.gif)

2020-06-23 18:44 UTC, ferblape approved these changes

2020-06-24 11:31 UTC, Crashillo requested changes

2020-06-24 11:31 UTC, Crashillo commented on app/javascript/gobierto_data/lib/factories/datasets.js
> +        })
Why must a `factory` know the error response calls a router action? You're mixing unrelated concepts. A couple of thing here:

1. `getDatasetMetadata` shouldn't be async. It only returns a promise
2. `.then(response => { return response })` REALLY? 😒 Remove that clause
3. No catches here. Handle the catch error where `getDatasetMetadata` is being called, wrapping it into a try-catch block.

2020-06-30 05:24 UTC, ferblape commented
Ping @Crashillo

2020-07-01 09:54 UTC, Crashillo approved these changes

2020-07-01 09:55 UTC, merged