Gobierto Data / Upgrade Perspective: 0.4.2 → 0.5.1
PopulateTools/gobierto pull request #3233
Opened 2020-07-14 13:18 UTC by jorgeatgu

Closes https://github.com/PopulateTools/issues/issues/1080

## :v: What does this PR do?

Update Perspective from 0.4.2 to 0.5.1

Major change: It replace `@finos/perspective-viewer-hypegrid` which built the `table` with `canvas`, with `@finos/perspective-viewer-datagrid`, which builds the `table` with pure `HTML`.

Includes another `webpack` loader, it's necessary for the new `table`...

## :mag: How should this be manually tested?

Staging

## :eyes: Screenshots

### Before this PR

![Screenshot 2020-07-14 at 15 17 15](https://user-images.githubusercontent.com/2649175/87430181-2492bb00-c5e5-11ea-8eff-be806624807e.png)

### After this PR

2020-07-16 04:52 UTC, ferblape commented
@jorgeatgu do you know why these columns from [licitaciones](https://getafe.gobify.net/datos/licitaciones/editor), which are both dates, are displayed different?

![Screenshot 2020-07-16 at 06 51 32](https://user-images.githubusercontent.com/17616/87628291-e0143600-c730-11ea-97ee-432ce6a6be11.png)

2020-07-17 14:14 UTC, jorgeatgu commented
@ferblape 

These days I've been rereading the Perspective documentation. I read this:

> In some cases, the inferrence algorithm may not return exactly what you'd like. For example, a column may be interpreted as a datetime when you intended it to be a string, or a column may have no values at all (yet), as it will be updated with values from a real-time data source later on.

[Perspective docs](https://perspective.finos.org/docs/md/js.html#loading-data-with-table)

So I've taken the types from each dataset, and loaded them into Perspective. Now(in local, not staging😅) it doesn't transform the dates.

![Screenshot 2020-07-17 at 16 08 19](https://user-images.githubusercontent.com/2649175/87795029-c87ba100-c847-11ea-8c01-0e418958e61c.png)


https://github.com/PopulateTools/gobierto/blob/a675dc56a327ab3c8e4be36fa5da7d310c6df509/app/javascript/gobierto_data/webapp/components/commons/Visualizations.vue#L106-L108

But there's a little problem. Perspective supports the following types:
```
integer
float
boolean
date
datetime
string
```

We have many more types, so if we pass you one of our types, the Visualization returns an error. The solution, transform our types into Perspective types https://github.com/PopulateTools/gobierto/blob/a675dc56a327ab3c8e4be36fa5da7d310c6df509/app/javascript/gobierto_data/webapp/components/commons/Visualizations.vue#L92-L102

[And, we can override Perspective settings](https://perspective.finos.org/docs/md/js.html#customizing-behavior-with-perspectiveconfigjs)

2020-07-20 08:32 UTC, ferblape commented
Sounds a good approach to me

2020-07-24 06:43 UTC, ferblape commented
In https://demo-datos.gobify.net/datos/datadista-ccaa-covid19-datos-isciii/editor, this query breaks perspective because can't find date column:

```sql
SELECT fecha::date as date, * 
FROM datadista_ccaa_covid19_datos_isciii 
ORDER by date DESC
LIMIT 50
```

2020-07-24 07:28 UTC, jorgeatgu commented
@ferblape 

I added another check, and replaces `some` for `every`. Try it again

![Screenshot 2020-07-24 at 09 26 20](https://user-images.githubusercontent.com/2649175/88369211-d3768a00-cd8f-11ea-8eef-9f3addca0657.png)

2020-07-24 10:04 UTC, ferblape approved these changes

2020-07-28 04:46 UTC, ferblape commented
ping @Crashillo

2020-07-28 07:10 UTC, Crashillo requested changes

2020-07-28 07:10 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Visualizations.vue
> +      const sameColumns = arrayColumnsFromAPI.length == arrayColumnsFromQuery.length && arrayColumnsFromAPI.every(column => arrayColumnsFromQuery.includes(column))
Use three equals in comparisons

```suggestion
      const sameColumns = arrayColumnsFromAPI.length === arrayColumnsFromQuery.length && arrayColumnsFromAPI.every(column => arrayColumnsFromQuery.includes(column))
```

2020-07-28 07:10 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Visualizations.vue
> +        }
You should merge the clauses of the same conditions:

```
if (transformColumns[key] === 'hstore') || (transformColumns[key] === 'jsonb') ... {
   transformColumns[key] = 'string'
....
```

2020-07-28 09:28 UTC, Crashillo approved these changes

2020-07-28 09:30 UTC, merged