Gobierto Data / Transforms Booelan values and show errors
PopulateTools/gobierto pull request #3511
Opened 2020-11-25 17:18 UTC by jorgeatgu

Closes 

https://github.com/PopulateTools/issues/issues/1081
https://github.com/PopulateTools/gobierto/issues/3434

## :v: What does this PR do?

Postgresql returns boolean values as `t` and `f`, doesn't understand that `f` is `false` and `t` is `true,` so we have to transform those values.

When the user tries to save an invalid query, nothing happens. Now we catch the error and show it.

## :mag: How should this be manually tested?

Staging

2020-11-25 21:04 UTC, ferblape commented
Hmmm, about the error in a query, I don't agree with what you call the error message ;)

For example, if I write this wrong query the error message is No Reason Phrase (??):

![Screenshot from 2020-11-25 22-01-00](https://user-images.githubusercontent.com/17616/100281275-e9789f00-2f69-11eb-8acb-1f30aa00bcf6.png)

While the API returns a different error message:

![Screenshot from 2020-11-25 22-01-11](https://user-images.githubusercontent.com/17616/100281278-ea113580-2f69-11eb-8e6f-7fe6b653bdeb.png)

Some screenshots in the PR would help be appreciated too

2020-11-26 07:25 UTC, jorgeatgu commented
My mistake. I thought the error in executing an invalid query was the same as trying to save an invalid query, but it is a little different.

Update:
![Screen Recording 2020-11-26 at 08 15 43 2020-11-26 08_19_30](https://user-images.githubusercontent.com/2649175/100319808-8b2adb00-2fc0-11eb-97ad-91ac0fe5ace0.gif)

2020-11-26 07:59 UTC, ferblape approved these changes

2020-11-26 08:49 UTC, Crashillo requested changes
Actually I don't like this way to face it the Boolean issue (it happened the same for ISCIII). We shouldn't be parsing the Boolean values all the time. I think this problem belongs to postgres response or perhaps the CSV conversion.

Thoughts, @ferblape @jorgeatgu ?

2020-11-26 08:49 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/Dataset.vue
> +          this.queryError = detail
In one line 😄 
```suggestion
        } catch ({ response: { data: { errors: [{ detail } = {}] = [] }}}) {
          this.queryError = detail
```

2020-11-26 08:49 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/Dataset.vue
> +          this.queryError = detail
DRY

2020-11-26 08:49 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Visualizations.vue
> +      const replaceBooleanValues = this.items.replace(/"t"/g, '"true"').replace(/"f"/g, '"false"')
Does`this.items` contain only Booleans?

2020-11-26 08:52 UTC, Crashillo commented
FYI, I edited the OP to fix the _Closes_ triggers. They should be in the first line of the issue you wanna close. At the sidebar, now you can _link_ these issues as well

2020-11-26 08:56 UTC, jorgeatgu commented
> Actually I don't like this way to face it the Boolean issue (it happened the same for ISCIII). We shouldn't be parsing the Boolean values all the time. I think this problem belongs to postgres response or perhaps the CSV conversion.
> 
> Thoughts, @ferblape @jorgeatgu ?

Postgresql always return `true` as `t` and `false` as `f` @entantoencuanto 

I don't like this solution either, but I think it's the only one.

2020-11-26 08:59 UTC, Crashillo commented
What if? `SELECT true::boolean::text, false::boolean::text`

https://www.postgresql.org/message-id/CACfv+pJbG5fLWOgSfZaTKR0_w3Rbx3XqTphD7Pndp3ygvEOB-A@mail.gmail.com

2020-11-26 09:06 UTC, Crashillo commented
It's OK that PostgresQL deals with 't'/'f'. That's not the point. But the issue I believe it is at the conversion to JSON/CSV

2020-11-26 11:41 UTC, jorgeatgu commented
Another approach:

The first step, check if the columns contain `Boolean` values https://github.com/PopulateTools/gobierto/blob/74552faadd1858e6b0387124bac25cbcefbb0423/app/javascript/gobierto_data/webapp/components/commons/Visualizations.vue#L96

If columns contain `Boolean`, goes to transform only these columns, convert `string` to `JSON`

https://github.com/PopulateTools/gobierto/blob/74552faadd1858e6b0387124bac25cbcefbb0423/app/javascript/gobierto_data/webapp/components/commons/Visualizations.vue#L214-L234

And the last step: convert `JSON` to `CSV`

Test:

![Screenshot 2020-11-26 at 12 38 46](https://user-images.githubusercontent.com/2649175/100346632-719b8a80-2fe4-11eb-841b-6590f1b76815.png)

2020-11-26 12:43 UTC, Crashillo reviewed
So we're converting String -> JSON -> CSV, just for check Boolean values. Interesting. Could you please, test perfomance with large files?

2020-11-26 13:42 UTC, Crashillo commented
I would save those transformations. I'd replace it straight outta file 🏋🏾‍♀️. For example, `this.items` has:
```csv
\"España\",\"espana\",\"8460261\",\"0.0\",,,,,,,,,,,,,,,\"f\"
```
So, try something like `this.items.replaceAll("\"f\"", false)` instead of all those hacky-tricky-diabolic transformations

2020-11-27 06:50 UTC, ferblape commented
Ping me to discuss

Context: we can't change how postgres returns booleans, and we can't put a Ruby layer in the middle, because we lose all the speed of Postgres, so it must be done in the client.

My proposal: would it make sense to update the boolean values here only if the column type is boolean? https://github.com/PopulateTools/gobierto/pull/3511/commits/7653b4669c30b7ecc67ac269df063740c242eb72#diff-39e9cd514806cd05c4df2cddbce712c0761c3b080515df459d07bc60442b35afL107-L120

2020-11-27 09:19 UTC, Crashillo commented
> would it make sense to update the boolean values here only if the column type is boolean?

@jorgeatgu do we know what sort of columns (datatypes) we have BEFORE initialize perspective? If so, the only thing (I believe) we can do is about checking whether any column is boolean, therefore, we apply the `replace` clause. In other words, only replace if some column is boolean.
But I'm afraid we cannot replace ONLY booleans because the input is a large string (plain text)

2020-11-27 09:31 UTC, jorgeatgu commented
@ferblape 

@Crashillo Yes, the API returns the type of the columns.

Right now this [function](https://github.com/PopulateTools/gobierto/blob/74552faadd1858e6b0387124bac25cbcefbb0423/app/javascript/gobierto_data/webapp/components/commons/Visualizations.vue#L204-L212) checks if some column has a `boolean` value, if contains some Boolean columns another function _hacky-tricky-diabolic transformations_  to `t` and `f` to `true` and `false`.

2020-11-27 09:55 UTC, Crashillo requested changes

2020-11-27 09:55 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Visualizations.vue
> +      let replaceItems = datasetsHasBooleanColumns.length > 0 ? this.replaceBooleanValues(this.items) : this.items
You complicate things a lot

```suggestion
      let replaceItems = this.items
      if (this.objectColumns.some(({ value }) => value === "boolean" )) {
        replaceItems = this.items.replace(/"t"/g, '"true"').replace(/"f"/g, '"false"')
      }
```

2020-11-27 09:56 UTC, Crashillo commented on app/javascript/gobierto_data/webapp/components/commons/Visualizations.vue
> +      let replaceItems = datasetsHasBooleanColumns.length > 0 ? this.replaceBooleanValues(this.items) : this.items
And remove the `checkIfBooleanExist` function, sure

2020-11-27 10:22 UTC, Crashillo approved these changes

2020-11-27 15:38 UTC, ferblape approved these changes

2020-11-27 15:38 UTC, merged