Gobierto Visualizations / Vue Table Component
PopulateTools/gobierto pull request #3648
Opened 2021-01-22 16:33 UTC by jorgeatgu

Closes #3596 

## :v: What does this PR do?

- Create a table as a new `Vue` component
- Implement the new table in Contracts and Subsidies.
- Remove old components, Table and TableRow.

⚠️ Warning this PR introduces `jest`, we need research how to` import Vue-directives/filters` to avoid errors. For example, we need to [import i18n again](https://github.com/PopulateTools/gobierto/compare/3596_vue_table_component?expand=1#diff-6e44e909b696e1f297971ccc74e7cfdbb1ea5c91597a2b0eb33b2370dae866f7R34-R39) to pass the tests without errors.

## :mag: How should this be manually tested?

[Contracts Summary](https://getafe.gobify.net/visualizaciones/contratos/)
[Contracts Show](https://getafe.gobify.net/visualizaciones/contratos/adjudicaciones)
[Contracts Assignee](https://getafe.gobify.net/visualizaciones/contratos/adjudicaciones/1057964)
[Subsidies Summary](https://getafe.gobify.net/visualizaciones/subvenciones/)
[Subsidies Show](https://getafe.gobify.net/visualizaciones/subvenciones/subvenciones)

### After this PR

![Screen Recording 2021-01-22 at 17 26 35 2021-01-22 17_32_47](https://user-images.githubusercontent.com/2649175/105517877-dff48480-5cd7-11eb-8260-bcb364a939ba.gif)

2021-01-25 15:25 UTC, Crashillo requested changes
IMO, this is not a reusable component. It's just a sugar code.

2021-01-25 15:25 UTC, Crashillo commented on app/assets/stylesheets/comp-vue-table.scss
> +  }
Avoid unnecessary nesting

2021-01-25 15:25 UTC, Crashillo commented on app/assets/stylesheets/comp-vue-table.scss
> +    }
Same

2021-01-25 15:25 UTC, Crashillo commented on app/assets/stylesheets/comp-vue-table.scss
> +      max-width: 35vw;
Too narrow for mobile, isn't it?

2021-01-25 15:25 UTC, Crashillo commented on app/assets/stylesheets/comp-vue-table.scss
> +      max-width: 40vw;
Same

2021-01-25 15:25 UTC, Crashillo commented on app/assets/stylesheets/comp-vue-table.scss
> +    }
No nesting, and don't use font-awesome classes, here you may use `i`

2021-01-25 15:25 UTC, Crashillo commented on app/assets/stylesheets/comp-vue-table.scss
> +      width: 25vw;
Mobile?

2021-01-25 15:25 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/Table.vue
> +    data-testid="table-component"
What for?

2021-01-25 15:25 UTC, Crashillo commented on app/javascript/lib/commons/setup-test.js
> +import $ from "jquery";
Remove this file

2021-01-25 15:25 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/Table.vue
> +    <Pagination
Pagination should be an `slot`, you're enforcing always to have a pagination component

2021-01-25 15:25 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/Table.vue
> +                    <a href="#">{{ item[field] }}</a>
empty link? what's that?

2021-01-25 15:25 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/Table.vue
> +        :toggle-visibility="toggleVisibility"
How this work? A slot cannot receive props, indeed, it's nonsense

2021-01-25 15:25 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/Table.vue
> +                    {{ money(item[field]) }}
Use better a filter
```suggestion
                    {{ item[field] | money }}
```

2021-01-25 15:25 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/TableColumnsSelector.vue
> +      labelCustomizeColumns: I18n.t("gobierto_plans.plan_types.show.customize_columns") || ''
A component with translations binded to gobierto_plans? No way

2021-01-25 15:25 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/Table.vue
> +            :to="{ name: routingMember, params: {id: item[routingId] } }"
What if I don't want to make the cells enroutable? What if `item` has no `routingId`? This template cannot be like that

2021-01-25 15:25 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/Table.vue
> +              <template v-else-if="type === 'truncate'">
What's a truncate cell type? Indeed, what's the difference with the default one? It's just wrapped with an `span`?

2021-01-25 15:25 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/Table.vue
> +      const id = this.currentSortColumn.field || this.orderColumn;
`this.currentSortColumn` is an String by default. Then it becomes an object? What's that?

2021-01-25 15:25 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/Table.vue
> +    },
This cannot be there. `toggleVisibility` is not something that Table.vue manages, but the ColumnSelector

2021-02-04 17:29 UTC, Crashillo commented
Conflicts pending

2021-02-05 06:29 UTC, jorgeatgu commented
> Conflicts pending

Ready to review

2021-02-05 09:40 UTC, Crashillo requested changes

2021-02-05 09:40 UTC, Crashillo commented on app/assets/stylesheets/comp-vue-table.scss
> +    }
Nesting

2021-02-05 09:40 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/TableColumnsSelector.vue
> +      labelCustomizeColumns: I18n.t("gobierto_plans.plan_types.show.customize_columns") || ''
Still pending

2021-02-05 09:40 UTC, Crashillo commented on app/javascript/gobierto_visualizations/webapp/containers/subsidies/Summary.vue
> +        :row-clickable="false"
Remove this prop

2021-02-05 09:40 UTC, Crashillo commented on app/javascript/gobierto_visualizations/webapp/containers/contracts/ContractsIndex.vue
> +      :row-clickable="true"
Remove this prop

2021-02-05 09:40 UTC, Crashillo commented on app/javascript/lib/vue-components/modules/Table.vue
> +    }
It's redundant declaring `onRowClick` as a function, and then, add another prop `rowClickable` to set the styles.

A row should be clickable (cursor), when `onRowClick` has any value. So, first off, remove the `rowClickable` prop. Then, set `default: null` for onRowClick. And lastly, create a computed prop who checks whether onRowClick is defined or not. If so, you may something like:

```vue
<tr
  :key="index"
  :class="{ 'is-clickable': isRowClickable }"
  class="gobierto-table__tr"
  @click="isRowClickable ? onRowClick(item) : null"
>
```
```vue
computed: {
  isRowClickable() {
    return !!this.onRowClick
  }
}
```

2021-02-05 11:14 UTC, Crashillo approved these changes

2021-02-05 11:39 UTC, ferblape commented
When I add multiple columns and scroll to the right, the link to configure columns moves to the left, while it should stay fixed in the right of the menu. Is it easy to fix?

![Screenshot from 2021-02-05 12-38-17](https://user-images.githubusercontent.com/17616/107029327-230e2780-67af-11eb-904f-71c0eb7cf715.png)

2021-02-05 12:46 UTC, jorgeatgu commented
> When I add multiple columns and scroll to the right, the link to configure columns moves to the left, while it should stay fixed in the right of the menu. Is it easy to fix?
> 
> ![Screenshot from 2021-02-05 12-38-17](https://user-images.githubusercontent.com/17616/107029327-230e2780-67af-11eb-904f-71c0eb7cf715.png)

Fixed. Now the column selector is sticky while scrolling the table.
![Screen Recording 2021-02-05 at 13 43 19 2021-02-05 13_45_42](https://user-images.githubusercontent.com/2649175/107035465-83559700-67b8-11eb-9d4e-7e31dec18914.gif)

2021-02-06 06:43 UTC, merged