Embed visualizations
PopulateTools/gobierto pull request #3747
Opened 2021-03-03 16:05 UTC by Crashillo

Closes https://github.com/PopulateTools/issues/issues/1218

## :v: What does this PR do?
Allow embed data visualizations from GobiertoAPI in external sites. [Further referecence](https://populate.getoutline.com/doc/gobierto-data-visualizations-embed-PluB5kUNBA)

2021-03-04 05:46 UTC, ferblape requested changes
It's not working to me. See where I'm embedding it:

http://downloads.blat.es/test.html

What am I doing wrong? @Crashillo

2021-03-04 08:22 UTC, Crashillo commented
Perhaps, it's related to the layout you're implementing. Just for checking, set this style at the body tag: `style="height: 100vh;display:grid;grid-template-columns:1fr 1fr;"` and reload with it

2021-03-04 08:34 UTC, Crashillo commented
Yep, definitely, it's a layout issue. I believe I've to set, at least, width & height for the `div` containing the viewer, or even, replace the container itself in order to hide a bit the token

2021-03-04 13:24 UTC, jorgeatgu requested changes

2021-03-04 13:24 UTC, jorgeatgu commented on app/javascript/gobierto_embeds/index.js
> +    if (query_id) {
```suggestion
const url = query_id ? `${site}/api/v1/data/queries/${query_id}.csv` : sql ? `${site}/api/v1/data/data.csv?sql=${encodeURIComponent(sql)}` : null
```

2021-03-05 11:32 UTC, Crashillo commented on app/javascript/gobierto_embeds/index.js
> +    if (query_id) {
Done

2021-03-05 14:13 UTC, merged