Gobierto Data / Testing embed
PopulateTools/gobierto pull request #3900
Opened 2021-06-03 13:54 UTC by jorgeatgu

Closes #https://github.com/PopulateTools/issues/issues/1293

## :v: What does this PR do?
Waiting

## :mag: How should this be manually tested?

## :📹: Video

[LOOM](https://www.loom.com/share/6755cf25405949e4a9df394cb4d42fc4)

2021-06-03 15:21 UTC, ferblape requested changes
Loooking great! Could you add an extra step in CircleCI to run javascript? You just need to copy a existing one and instead of running bin/rails test just run `yarn run test`

2021-06-08 09:12 UTC, ferblape commented on .circleci/config.yml
> +            TEST="$(find test -path '*javascript*' -name '*.test.js' | circleci tests split --split-by=timings)"
This is not necessary ;)

2021-06-08 09:12 UTC, ferblape commented on test/javascript/gobierto_data/__mocks__/data.json
> +{
Yeah

2021-06-10 10:03 UTC, Crashillo approved these changes

2021-07-20 14:44 UTC, merged