1319 cms custom fields
PopulateTools/gobierto pull request #3927
Opened 2021-08-17 21:14 UTC by entantoencuanto

Closes  PopulateTools/issues#1319

## :v: What does this PR do?
* Creates a model inherited from `GobiertoCommon::Collection` in GobiertoCms for pages collection
* Allows the definition of custom fields for pages of CMS collections
* Adds the management of custom fields of CMS pages using the definition at collection level
* Adds a configuration to avoid the definition of custom fields on CMS page at global module level

## :mag: How should this be manually tested?
Visit a site with at least one CMS collection and define custom fields on them. The admin of pages belonging to the collection should display the custom fields and they should be editable

## :eyes: Screenshots

### Before this PR

### After this PR

## :shipit: Does this PR changes any configuration file?

- [ ] new environment variable in `.env.example`?
- [ ] new entry in `config/application.yml`?
- [ ] new entry in `config/secrets.yml`?

(Changes in these files might need to update the role in Ansible)

## :book: Does this PR require updating the documentation?

- [ ] new site configuration variable?
- [ ] new site template?
- [ ] new module/submodule settings?
- [ ] significant changes in some feature?

2021-08-18 05:38 UTC, ferblape requested changes
When I create a new page in the collection, custom fields are not available, i.e  see https://burjassot.gobify.net/admin/cms/pages/new?collection_id=266748

But when I edit an existing page in that collection custom fields are available.

2021-08-18 10:00 UTC, entantoencuanto commented
Fixed!

2021-08-18 15:14 UTC, furilo commented
- [ ] I can't change the id of an already created custom field. I get this error: "Instance class name no es válido" - Tried in https://fnd.gobify.net/admin/custom_fields/369
- [ ] If user is in the Custom fields page, and the module has only one instance type, maybe we can direct the user directly to it's page, avoiding the extra click of https://fnd.gobify.net/admin/custom_fields/module_resources/gobierto_cms-pages_collection/instance_level_resources/266751

2021-08-20 15:25 UTC, furilo commented
Good on my side.

2021-08-25 09:18 UTC, entantoencuanto commented
Hi, can we merge this PR? This is required to generate a new feature sidebar
cc/ @ferblape

2021-08-25 10:11 UTC, ferblape commented
Yes, sorry

El mié., 25 ago. 2021 11:18, Eduardo Martínez ***@***.***>
escribió:

> Hi, can we merge this PR? This is required to generate a new feature
> sidebar
> cc/ @ferblape <https://github.com/ferblape>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PopulateTools/gobierto/pull/3927#issuecomment-905329279>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAEJUBIYHKA2KXVUJQ2NE3T6SYODANCNFSM5CKV5IVA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-25 10:13 UTC, merged