[WIP] - 627 - Set IBM Notes credentials from admin interface.
PopulateTools/gobierto pull request #662
Opened 2017-04-24 13:25 UTC by amiedes

Connects to #627 

### What does this PR do?

This PR ads the possibility for a site admin to set IBM Notes credentials from a GUI.

Also, credentials are now stored as `GobiertoModuleSettings` instead of
`GobiertoPeople::Setting`. This commit contains a migration to perform
the corresponding data transformations.

### How should this be manually tested?

IBM Notes integration should keep working after this update.

### Does this PR changes any configuration file?

No

2017-04-25 05:06 UTC, ferblape commented
Why is this branch not in master and why is a WIP? Everything that is required to be reviewed should be in master, and everything that is a WIP should be explicit about why is WIP.

2017-04-25 05:14 UTC, ferblape requested changes
Code looks good. Please, add the changes I have requested and feel free to merge in master again and release to staging.

2017-04-25 05:14 UTC, ferblape commented on app/views/gobierto_admin/gobierto_people/configuration/settings/edit.html.erb
> +        <%= f.text_field :ibm_notes_pwd, placeholder: t(".placeholders.ibm_notes_pwd") %>
This should be a password_field, to be more private.

2017-04-25 05:14 UTC, ferblape commented on app/forms/gobierto_admin/gobierto_people/settings_form.rb
> +
I think we should add a validation in the form: if the user selects IBM Notes integration but user and password are empty, we should display an error message that credentials are required.

2017-04-25 05:14 UTC, ferblape commented on app/views/gobierto_admin/gobierto_people/configuration/settings/edit.html.erb
> +
Are you going to add the javascript code to clean the form? Is that why it's a WIP?

2017-04-25 07:17 UTC, amiedes commented
I marked this as WIP because wanted to add also the JS code and the solution for the issues exposed in #627. I didn't deploy to staging because I wanted you to take a look at the migration script previously.

I'll try to be explicit about this things from now on 👌

2017-04-27 11:08 UTC, amiedes commented
Deployed to staging 🚀 

The migration worked correctly but since it only deleted "deprecated" `GobiertoPeople::Setting` containing the key `IBM_NOTES_etc.`, I had to delete old `LOTUS_NOTES_etc.` settings manually from the console.

A few notes:

* I think the feedback provided by the error messages shown in the interface can be improved. Right now it only says "An error occured when saving this settings", but I couldn't guess how to customize it to say "Credentials can't be blank" etc.

2017-04-27 17:27 UTC, ferblape approved these changes

2017-04-27 17:27 UTC, merged