648 - Change person agenda
PopulateTools/gobierto pull request #667
Opened 2017-04-26 09:50 UTC by amiedes

Connects to #648 

### What does this PR do?

Adds the features specified in the issue description:

* Removes the upper subscribe box from a person agenda.
* Adds the calendar widget in the sidebar of a GobiertoPeople person agenda.
* When only agendas submodule is enabled, the submodules menu in the GobiertoPeople people sidebar is removed.
* When the officials submodule is not active, the "Biography and CV" option in the submodules menu in the GobiertoPeople people sidebar is removed.

Also does some improvements to GobiertoPeople events index:

* Fixes bug in GobiertoPeople events index. When clicking on a past date link on the calendar widget and being on the future events controller, a "No future events" message was being rendered. It's obvious that when clicking on a past date, events will never be future.
* Adds some integration tests related to the calendar widget usage in GobiertoPeople events index.

### How should this be manually tested?

When browsing Gobierto, the upper requirements should be meeted.

### Does this PR changes any configuration file?

No

2017-04-26 13:31 UTC, ferblape requested changes

2017-04-26 13:31 UTC, ferblape commented on app/views/gobierto_people/people/_navigation.html.erb
> +<% if (controller_name == "person_events" || controller_name == "past_person_events") && action_name == "index" %>
Can we change the condition to `if @calendar_events.any?` ?

2017-04-26 13:31 UTC, ferblape commented on app/views/gobierto_people/people/_navigation.html.erb
> +        <%= link_to date.day, date: date, start_date: params[:start_date] %>
You can remove the if / else: `<%= link_to_if events.any?, date.day, date: date, start_date: params[:start_date] %>`

2017-04-26 13:31 UTC, ferblape commented on app/views/gobierto_people/people/person_events/index.html.erb
> +    <div class="events-filter">
Is `<div class="events-filter">` duplicated?

2017-04-26 13:31 UTC, ferblape commented on test/support/person_event_helpers.rb
> +  def create_event(options = {})
👍

2017-04-26 13:31 UTC, ferblape commented on app/controllers/gobierto_people/people/person_events_controller.rb
> +        @calendar_events = @person.events
Maybe you can extract `@calendar_events` to a filter so it'll apply to `PastPersonEvents`

2017-04-26 14:20 UTC, amiedes commented on app/views/gobierto_people/people/_navigation.html.erb
> +<% if (controller_name == "person_events" || controller_name == "past_person_events") && action_name == "index" %>
Do we want to hide the calendar widget if no events have been created yet? I'd leave it.

If we don't want to hide it, we can change to something like `!@calendar_events.nil?`, but I don't see it as a huge win.

2017-04-26 14:35 UTC, ferblape commented on app/views/gobierto_people/people/_navigation.html.erb
> +<% if (controller_name == "person_events" || controller_name == "past_person_events") && action_name == "index" %>
right, it should be `if @calendar_events`, because we want to show the calendar always, for consistency

2017-04-26 14:46 UTC, amiedes commented
Done! Deploying to staging again...

2017-04-27 08:07 UTC, ferblape approved these changes

2017-04-27 08:07 UTC, merged

2017-04-27 08:08 UTC, amiedes commented
Thx!