723 - Attachments admin API
PopulateTools/gobierto pull request #747
Opened 2017-06-09 14:46 UTC by amiedes

Connects to #723 

### What does this PR do?

Creates simple API to manage attachments and attachings from admin windows.

### Does this PR changes any configuration file?

**NOTE**: The `GobiertoAttachments::Attachment` Algolia index must be created in production.

2017-06-09 16:21 UTC, ferblape commented on test/integration/gobierto_admin/gobierto_attachments/api/attachments_test.rb
> +        unexistent_id = 666
:six::six::six:

2017-06-09 17:05 UTC, ferblape commented
Good work @amiedes! I have done a quite exhaustive testing with really bad ideas in my mind and everything worked as I expected. 

There are just a few things that need to be improved a bit:

- [ ] When an Attachment is going to be created and already exists in the same site other with the same content (same md5) I think we should try to avoid duplicates and return something different to 200 OK. Maybe a validation error and include in the error message the link to the existing resource?

- [ ] Capture this exception: https://rollbar.com/fernando/gobierto/items/437/

- [ ] Capture this exception (missing file field in the body of the create request): https://rollbar.com/fernando/gobierto/items/436/

- [ ] There's no action show in attachments! We should implement it

- [ ] This request `http://santboi.gobify.net/admin/attachments/api/attachments?attachable_type=GobiertoCms::Page&attachable_id=8` returns a 200 OK and responds in HTML

2017-06-09 17:11 UTC, ferblape requested changes

2017-06-09 17:11 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_attachments/api/attachments_controller.rb
> +          if params[:search_string]
`attachments = if ... elsif .. else`, to avoid the assignment of the variable three times

2017-06-09 17:11 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_attachments/api/attachments_controller.rb
> +          attachment.save!
new + save! = create!, right?

2017-06-09 17:11 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_attachments/api/attachments_controller.rb
> +          @tmp_file = Tempfile.new('attachment_file')
Why instance variable?

2017-06-09 17:11 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_attachments/api/attachments_controller.rb
> +          file_content = Base64.decode64(attachment_params[:file])
We should use `strict_decode64`

2017-06-15 09:17 UTC, ferblape requested changes
We need to translate error messages
Also, we should translate Attachment attributes (file size, file name, file digest...)

2017-06-15 09:17 UTC, ferblape commented on app/models/gobierto_attachments/attachment.rb
> +        "not unique (already uploaded at #{url})."
Translate this message

2017-06-15 09:17 UTC, ferblape commented on app/models/gobierto_attachments/attachment.rb
> +          errors.add(:base, "File exceeds max size")
Translate this message, please

2017-06-15 18:53 UTC, amiedes commented
@ferblape, does it make sense to make the translations given that the only reason why the locale is available is because we haven't yet implemented a token-based authorization?

2017-06-16 06:36 UTC, ferblape commented
Well, the API should be available with any locale, no matter if it's an admin api. Imagine a customer building their website using Gobierto events, and they want the site to be in Catalan.

2017-06-16 06:37 UTC, ferblape commented
Also, consider I'm going to be using the API to display error messages to the administrators in the frontend. If the UI is in Spanish and the error message in English, the experience will be bad.

2017-06-19 10:19 UTC, amiedes commented
@ferblape Done!

2017-06-19 14:14 UTC, ferblape approved these changes

2017-06-19 14:14 UTC, merged