Budget guide
PopulateTools/gobierto pull request #797
Opened 2017-07-11 16:23 UTC by martgnz

Connects to #742.

### What does this PR do?
This PR adds a sandbox page with a draft of the budget guide based on the proposed design. At the moment the page is only in Spanish.

There are two places which I need help to integrate, as I want to display the total income and expenses of the current city. We also need to make the transform the HTML anchors to Rails `link_to`.

Extra ball: the header on sandbox pages should be displayed correctly now.

### How should this be manually tested?
Go to [http://madrid.gobierto.dev/sandbox/budget_guide.html](http://madrid.gobierto.dev/sandbox/budget_guide.html).

2017-07-12 11:35 UTC, furilo requested changes

2017-07-12 11:35 UTC, furilo commented on app/assets/stylesheets/comp-content.scss
> +  @mixin circle($size) {
should we move this to populities?

2017-07-12 11:35 UTC, furilo commented on app/assets/stylesheets/comp-content.scss
> +    & > * {
Doesn't this type of things degrade performance? Or we should not worry about it?

2017-07-12 11:35 UTC, furilo commented on app/assets/stylesheets/comp-content.scss
> +  hr {
we already have some separators in comp-headings_blocks. Should we unify/reuse?

2017-07-12 11:35 UTC, furilo commented on app/views/sandbox/budget_guide.html.erb
> +  <main class="content">
We have a white space between the header and the gradient. This is the way it's supposed to be?

<img width="490" alt="captura de pantalla 2017-07-12 a las 13 25 23" src="https://user-images.githubusercontent.com/24740/28115523-999adc3a-6705-11e7-9ead-052a20174c3c.png">

2017-07-12 11:35 UTC, furilo commented on app/assets/stylesheets/comp-content.scss
> +      max-width: 630px;
I don't think it's a good practice to establish the width of every element. Isn't it simpler to specificy the width of the column? And then if you want the images to stand out, you can force them.

2017-07-12 11:35 UTC, furilo commented on app/views/sandbox/budget_guide.html.erb
> +        <h1>Así funciona un presupuesto municipal</h1>
I'd say: Cómo funciona un presupuesto municipal

2017-07-12 11:35 UTC, furilo commented on app/views/sandbox/budget_guide.html.erb
> +        <ul>
This is the TOC (table of contents). Should we give it a special/different format?

2017-07-12 11:35 UTC, furilo commented on app/views/sandbox/budget_guide.html.erb
> +      <%= image_tag 'illustrations/presupuestos.jpg', class: 'pure-img' %>
Right now the image is being pixalated. For this specific one, I would not make it so wide.

2017-07-12 11:35 UTC, furilo commented on app/views/sandbox/budget_guide.html.erb
> +      <%= image_tag 'illustrations/presupuestos.jpg', class: 'pure-img' %>
(but undoing its wideness it's not straightforward with the global redefinition rules ...)

2017-07-12 11:35 UTC, furilo commented on app/views/sandbox/budget_guide.html.erb
> +          <a href="#"><i class="fa fa-facebook"></i></a>
Pending to be integrated.

2017-07-12 11:35 UTC, furilo commented on app/views/sandbox/budget_guide.html.erb
> +        </ul>
Missing 
- Deuda viva: Cuánto debe tu municipio
- Ejecución presupuestaria

2017-07-12 11:35 UTC, furilo commented on app/views/sandbox/budget_guide.html.erb
> +      <div class="sources">
I'd add also the .note class

2017-07-12 13:49 UTC, ferblape commented
@martgnz which is the name of the class you want to be added in the `<body>`.

@furilo are we going to add a new section in the navigation for the guide?

2017-07-12 13:54 UTC, furilo commented
>
> @furilo <https://github.com/furilo> are we going to add a new section in
> the navigation for the guide?
>

Yes, and while you are at it, let's just leave:

Presupuesto (linking to the home) · Ejecución · Guía

2017-07-12 14:02 UTC, martgnz commented
@ferblape I would say for the moment let's add `budget-guide`.

2017-07-12 14:04 UTC, furilo commented
> @ferblape <https://github.com/ferblape> I would say for the moment let's
add budget-guide.

Let's go with "controller_action" names. That's enough, predictable and
simple.

2017-07-12 16:41 UTC, martgnz commented on app/assets/stylesheets/comp-content.scss
> +  hr {
To make them bigger than the container I had to add have specific margin rules, so they aren't as global as they could be. I would like to unify or reuse though.

2017-07-12 16:42 UTC, martgnz commented on app/views/sandbox/budget_guide.html.erb
> +  <main class="content">
No, but I need to have a body class to address this one as the margin is the header.

2017-07-12 16:43 UTC, martgnz commented on app/views/sandbox/budget_guide.html.erb
> +      <%= image_tag 'illustrations/presupuestos.jpg', class: 'pure-img' %>
Maybe we can have another class, like `img-small`. My main concern is the ability to integrate those with a CMS.

2017-07-12 16:44 UTC, martgnz commented on app/views/sandbox/budget_guide.html.erb
> +        <ul>
Yeah it makes sense! But I wanted to be as simple as possible.

2017-07-13 06:40 UTC, furilo commented on app/assets/stylesheets/comp-content.scss
> +  hr {
But why not extend an already existing class instead of creating a new one?

2017-07-13 06:40 UTC, furilo commented on app/views/sandbox/budget_guide.html.erb
> +  <main class="content">
OK

2017-07-13 07:00 UTC, ferblape commented
controller_action = `budgets_guide`

2017-07-13 13:59 UTC, furilo approved these changes

2017-07-14 07:56 UTC, merged