[WIP] Add Colection and ColectionItem models and tests
PopulateTools/gobierto pull request #799
Opened 2017-07-13 15:37 UTC by apradillap

Connects to #754

2017-07-13 16:35 UTC, ferblape approved these changes
👍 looks good to me!

2017-07-17 14:16 UTC, amiedes approved these changes

2017-07-21 14:49 UTC, ferblape requested changes
Just a couple of small issues:

![screen shot 2017-07-21 at 16 46 23](https://user-images.githubusercontent.com/17616/28468875-9e2d966c-6e34-11e7-9ee0-22ce7875b1c2.png)


1 - could you translate the attributes of the collection? (title, slug, container, item type). We use to do this in `config/locales/<module name>/models/<locale>.yml`, for example in GobiertoBudgetsConsultations

2 - why in the container dropdown hasn't any option? Maybe the sites are not yet included in the available containers?

2017-07-24 08:13 UTC, apradillap commented
@ferblape I translated ymls relation with collections and issues that I forgot in the previus PR. 
In addition, when selecting a container you can already select sites or issues.

I deployed in staging after several circle failures 😓

2017-07-24 10:22 UTC, ferblape approved these changes

2017-07-24 10:22 UTC, merged