[WIP] Gobierto Attachments Collections
PopulateTools/gobierto pull request #813
Opened 2017-07-24 13:44 UTC by apradillap

Connects to #755

2017-07-28 09:21 UTC, ferblape requested changes

2017-07-28 09:21 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_cms/file_attachments_controller.rb
> +      before_action { module_enabled!(current_site, 'GobiertoCms') }
We are not going to check if the module is enabled, all Gobierto accounts will have this module enabled.

2017-07-28 09:21 UTC, ferblape commented on config/locales/gobierto_admin/gobierto_cms/controllers/file_attachments/ca.yml
> +          success_html: El fitxer ha estat creada correctament. <a href="%{link}">Veure
Aquí sera: Veure el fitxer y no la página.

2017-07-28 09:21 UTC, ferblape commented on config/locales/gobierto_admin/gobierto_cms/controllers/file_attachments/ca.yml
> +          success_html: El fitxer ha estat creada correctament. <a href="%{link}">Veure
Por otro lado me parece bien cambiar a "Document" y no a fitxer o attachment. Este link a previsualizar debería de estar en los otros idiomas.

2017-07-28 09:21 UTC, ferblape commented on config/locales/gobierto_attachments/views/ca.yml
> +      gobierto_attachments_attachment_created: Fixer creat
Document

2017-07-28 14:46 UTC, ferblape commented
The breadcrumb of new / edit document page links to the pages list and not to the attachments list:

![screen shot 2017-07-28 at 16 39 46](https://user-images.githubusercontent.com/17616/28722432-0b66006e-73b4-11e7-9387-aad23cdf3209.png)

It should be "INICIO » DOCUMENTOS » <collection name>"

2017-07-28 15:10 UTC, apradillap commented
@ferblape Fixed https://github.com/PopulateTools/gobierto/pull/813/commits/6f06366e619732f6942002861c5fad0f5c598597

2017-07-29 07:34 UTC, ferblape approved these changes

2017-07-29 07:34 UTC, merged