804 - Admin CRUD for GobiertoParticipation::Process
PopulateTools/gobierto pull request #820
Opened 2017-07-25 15:06 UTC by amiedes

Connects to #804 

### What does this PR do?

TODO

### How should this be manually tested?

TODO

2017-07-26 09:55 UTC, ferblape requested changes

2017-07-26 09:55 UTC, ferblape commented on db/migrate/20170719091606_add_type_to_processes.rb
> +    add_column :gpart_processes, :process_type, :string, default: GobiertoParticipation::Process::GROUP
Why not an integer? It's faster to use integers as indexes that strings.

2017-07-26 09:55 UTC, ferblape commented on app/controllers/gobierto_admin/gobierto_participation/processes_controller.rb
> +      def create
We need to track an activity when a process is created / updated / deleted.

2017-07-26 09:55 UTC, ferblape commented on app/models/gobierto_participation/process.rb
> +    def self.allowed_types
Should we use an enum? It provides scopes, the method with the allowed values...

2017-07-26 09:55 UTC, ferblape commented on app/views/gobierto_admin/gobierto_participation/processes/_form.html.erb
> +                <%= (type == 'p') ? t('.process') : t('.group') %>
Don't use 'p' but the value through the model: `Process::PROCESS`

2017-07-26 09:55 UTC, ferblape commented on app/views/gobierto_admin/gobierto_participation/processes/_form.html.erb
> +          <h3>Tipo de grupo</h3>
Missing translation

2017-07-26 09:55 UTC, ferblape commented on app/views/gobierto_admin/gobierto_participation/processes/_form.html.erb
> +      <h3>Fases - Herramientas</h3>
Missing translation

2017-07-26 09:55 UTC, ferblape commented on app/assets/javascripts/admin/app/components/globalized_forms_component.js
> +    if (container == null) {
We prefer `===`

2017-07-26 09:55 UTC, ferblape commented on app/assets/javascripts/admin/app/components/globalized_forms_component.js
> +      var container = $(e.target).parents().filter("div .globalized_fields")
Reuse the variable `container`, don't declare a new one with `var`.

2017-07-26 09:55 UTC, ferblape commented on app/assets/stylesheets/admin/application.scss
> +// TODO: move somewhere else
Remove the TODO: @furilo confirmed we can keep it here.

2017-07-26 13:14 UTC, amiedes commented
🚀

2017-07-26 15:50 UTC, ferblape commented
A few more things:

1. Can we move the section Participation above the separator? It should be together with GobiertoPeople, Consultations....

![screen shot 2017-07-26 at 17 45 25](https://user-images.githubusercontent.com/17616/28630343-5a7dfb88-722a-11e7-9e8b-2c59ad1d86d1.png)

2. The button is below, it should be in the right column. Looks like there's a div not closed properly?

![screen shot 2017-07-26 at 17 45 03](https://user-images.githubusercontent.com/17616/28630344-5a7e900c-722a-11e7-8365-46feb614f42e.png)

3. Translate "Active"

![screen shot 2017-07-26 at 17 44 59](https://user-images.githubusercontent.com/17616/28630347-5ac62138-722a-11e7-97d5-be45c088df4d.png)

4. Translate "Starts" and "Ends"

![screen shot 2017-07-26 at 17 44 56](https://user-images.githubusercontent.com/17616/28630345-5a8d8a26-722a-11e7-91eb-fbe36916dbaf.png)

5. Information text shouldn't be here in the new form, it should be available in the tab after the process is created.

![screen shot 2017-07-26 at 17 44 51](https://user-images.githubusercontent.com/17616/28630348-5ac8f98a-722a-11e7-9ab0-bc3be449b536.png)

6. When editing a process / group, could we add the tabs from the sandbox?

7. I got a couple of Rollbars when creating the Process

https://rollbar.com/fernando/gobierto/items/475/?item_page=0&#instances

2017-07-28 08:07 UTC, ferblape requested changes

2017-07-28 08:07 UTC, ferblape commented on app/views/gobierto_admin/gobierto_participation/processes/_form.html.erb
> +              <h2>Editar fase: <%= stage_form.object.stage_type %></h2>
@amiedes, translate this and instead of the stage_type, render the translated string, please.

2017-07-28 08:07 UTC, ferblape commented on app/views/gobierto_admin/gobierto_participation/processes/_form.html.erb
> +                <% I18n.available_locales.map(&:to_s).each do |locale| %>
We don't use `I18n.avaiable_locales` anymore, but `current_site.configuration.available_locales`

2017-07-28 08:07 UTC, ferblape commented on app/views/gobierto_admin/gobierto_participation/processes/_form.html.erb
> +        <%= f.label :slug, t('.slug') %>
We don't provide custom translations to the form if we can avoid it. Translate the slug attribute as an ActiveRecord attribute. Same with many other strings in the form.

2017-07-28 08:07 UTC, ferblape commented on app/models/gobierto_participation/process.rb
> +    validates :slug, uniqueness: true
Slug is unique, yes, but in the scope of the site.

2017-07-28 08:07 UTC, ferblape commented on app/models/gobierto_participation/process_stage.rb
> +      self.write_attribute(:active, params[:active]) if params[:active]
You don't need to assign active explicitely, because it's an attr_accessor and gets assigned in the super.

2017-07-28 11:50 UTC, amiedes commented
I hope OK this time 🙈

2017-07-28 13:25 UTC, ferblape approved these changes

2017-07-28 13:51 UTC, merged