List of themes and view theme pages
PopulateTools/gobierto pull request #868
Opened 2017-08-14 16:07 UTC by apradillap

Connects to #829

2017-08-18 07:09 UTC, ferblape requested changes

2017-08-18 07:09 UTC, ferblape commented on config/locales/gobierto_participation/views/es.yml
> +        intro: Tus ideas ayudan a mejorar %{location_name} y la vida de todos los
This should be `intro_html` to don't escape the HTML:

![screen shot 2017-08-18 at 09 00 50](https://user-images.githubusercontent.com/17616/29447781-bed377c2-83f3-11e7-91c4-2a67b4264f55.png)

2017-08-18 07:09 UTC, ferblape commented on app/controllers/gobierto_participation/issues_controller.rb
> +      @processes = current_site.processes.process.open
Is there any reason you are not filtering the processes and the groups that belong to the current issue?

2017-08-18 07:09 UTC, ferblape commented on app/controllers/gobierto_participation/issues_controller.rb
> +      Issue.find_by_slug!(params[:id])
We should always filter by site. Two sites can have issues with the same slug.

2017-08-18 07:09 UTC, ferblape commented on test/integration/gobierto_participation/issues/issue_show_test.rb
> +  end
I miss a test that checks the processes and the groups of this issue.

2017-08-18 07:09 UTC, ferblape commented on app/views/gobierto_participation/processes/show.html.erb
> +              <%= link_to @process.issue.name, gobierto_participation_issue_path(@process.issue) %>
The link should use the `slug` not the `id` of the issue.

2017-08-18 13:29 UTC, apradillap commented on config/locales/gobierto_participation/views/es.yml
> +        intro: Tus ideas ayudan a mejorar %{location_name} y la vida de todos los
Fix it!! https://github.com/PopulateTools/gobierto/pull/868/commits/f9b7849cd40f84a39111766616d065ded802053e

2017-08-18 13:59 UTC, apradillap commented on app/controllers/gobierto_participation/issues_controller.rb
> +      @processes = current_site.processes.process.open
No, I forgot it

https://github.com/PopulateTools/gobierto/pull/868/commits/f1c3ee240e5bb4930543e445d9033a03be6d8126

2017-08-18 14:18 UTC, apradillap commented on app/controllers/gobierto_participation/issues_controller.rb
> +      Issue.find_by_slug!(params[:id])
https://github.com/PopulateTools/gobierto/pull/868/commits/4086b134aa46c779f25ed6d0342caa933e3073a4

I must have present multitenant, I reviewed other files

2017-08-18 14:18 UTC, apradillap commented on app/views/gobierto_participation/processes/show.html.erb
> +              <%= link_to @process.issue.name, gobierto_participation_issue_path(@process.issue) %>
Fix 
https://github.com/PopulateTools/gobierto/pull/868/commits/bc292e52644e987f570f9a79f610446ef31485b2

2017-08-18 23:04 UTC, apradillap commented on test/integration/gobierto_participation/issues/issue_show_test.rb
> +  end
https://github.com/PopulateTools/gobierto/pull/868/commits/806a4d8136f845a0ed7049f9a2e0bd81f38bc0da

2017-08-19 09:36 UTC, ferblape approved these changes

2017-08-19 09:42 UTC, merged