935 polls front
PopulateTools/gobierto pull request #958
Opened 2017-09-19 15:32 UTC by amiedes

Connects to #935 

### What does this PR do?

### How should this be manually tested?

### Does this PR changes any configuration file?

No

2017-09-20 06:55 UTC, ferblape requested changes
And you forgot this translation:

![screen shot 2017-09-20 at 08 47 05](https://user-images.githubusercontent.com/17616/30630531-51356bbe-9de1-11e7-8c25-47d25d8ee581.png)

Once you have fixed all the issues described please:

1. Assign the PR to Hugo, to fix the couple of things you have mentioned
2. Create a new issue for the improvements

👍

2017-09-20 06:55 UTC, ferblape commented on app/controllers/gobierto_participation/processes/poll_answers_controller.rb
> +      def create
Why not a before_filter? I.e. (from BudgetConsultations)

```ruby
      before_action :authenticate_user!
      before_action { verify_user_in!(current_site) }
```

2017-09-20 06:55 UTC, ferblape commented on app/controllers/gobierto_participation/processes/base_controller.rb
> +        @current_process ||= current_site.processes.find_by_slug!(params[:process_id])
You are not checking if the process is active.

2017-09-20 06:55 UTC, ferblape commented on app/views/layouts/_head.html.erb
> +<head>
👍

2017-09-20 09:54 UTC, amiedes commented
Hey @Crashillo, can you checkout this PR and fix the CSS issues?

We need to fix the upper right close button:

![image](https://user-images.githubusercontent.com/9287468/30637961-30678cb4-9dfa-11e7-869c-913d7a487b93.png)

And to add some styling to the "Next question" button when it has the `disabled` attribute set:

![image](https://user-images.githubusercontent.com/9287468/30638016-5e04da82-9dfa-11e7-8709-060cd425ae93.png)

2017-09-20 09:56 UTC, amiedes commented
Also I did a couple of hacks/workarounds. I'm not sure if they can stay like this:

![image](https://user-images.githubusercontent.com/9287468/30638093-94c761f2-9dfa-11e7-8cd1-0e99cfc92145.png)

2017-09-20 09:57 UTC, furilo commented
> I'm not sure if they can stay like this

No, they can't. 

@Crashillo let's wait until I give you the Gobierto intro.

2017-09-21 06:50 UTC, ferblape commented
@amiedes I have found something you need to fix, in this process in staging: http://participacion.gobify.net/processes/xadcasd

1. It doesn't have the polls stage activated, so it shouldn't show the link to "Encuestas" in the frontend
2. That action should have a kind of filter, so if you visit the url it should redirect to the home of the process
3. That URL doesn't show in the breadcrumb the name of the process

![screen shot 2017-09-21 at 08 50 08](https://user-images.githubusercontent.com/17616/30682415-e4e8ab78-9ea9-11e7-8d88-fe55b882976c.png)

2017-09-24 06:43 UTC, ferblape approved these changes

2017-09-26 10:57 UTC, ferblape commented
@amiedes could you take care of solving the conflicts and merging this branch to master?

2017-09-26 10:59 UTC, amiedes commented
Sure!

2017-09-26 13:44 UTC, merged